services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: pacem-backend
    ports:
      - "8000:8000"
    volumes: 
      - ./apps/backend:/app/backend
    working_dir: /app/backend
    command: ["python", "main.py"]

